(configuration-layer/declare-layer 'octave)
(configuration-layer/declare-layer 'org)
(configuration-layer/declare-layer 'latex)
(configuration-layer/declare-layer 'markdown)
(configuration-layer/declare-layer 'pdf-tools)
