(configuration-layer/declare-layer 'auto-completion)
(configuration-layer/declare-layer 'helm)
(configuration-layer/declare-layer 'emacs-lisp)
(configuration-layer/declare-layer 'git)
(configuration-layer/declare-layer 'spell-checking)
(configuration-layer/declare-layer 'syntax-checking)
(configuration-layer/declare-layer 'version-control)
